# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usbhid" "usb_storage" "uas" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/a9cbb95c-523c-4e81-90f1-33b0f4557a32";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."nixos-enc".device = "/dev/disk/by-uuid/5322a183-e08e-4a0a-a6bb-3ecd50516370";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/863b70ab-bf47-433d-b986-d87a9389e19b";
      fsType = "ext4";
    };

  fileSystems."/boot/efi" =
    { device = "/dev/disk/by-uuid/A54A-B011";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/4881627c-6d34-4add-bc3c-d3a0608370f6"; }
    ];

  nix.maxJobs = lib.mkDefault 8;
  powerManagement.enable = true;
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";

  systemd.mounts = [
    { description = "Games HDD";
      what = "/dev/disk/by-uuid/207acdf3-d70a-424b-9e36-fa719639a068";
      where = "/mnt/games";
      type = "ext4";
      options = "defaults";
      wantedBy = ["multi-user.target"];
    }
    { description = "Games HDD automount";
      where = "/mnt/games";
      wantedBy = ["multi-user.target"];
    }
  ];
}
