# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  boot.loader.grub.extraEntries = lib.mkIf config.boot.loader.grub.enable (lib.mkAfter ''
    menuentry "Shutdown" {
      halt
    }
    menuentry "Reboot" {
      reboot
    }
  '');
}
